In [56]:
# Analysis for Olympics medal count with economic power and population size per country 
#Olympic medals, economic power

In [57]:
import pandas as pd 
import json 
import matplotlib.pyplot as plt
import requests
import numpy as np
%matplotlib inline
import matplotlib as mpl


#load the data
csv_path = "../olympicsall.csv"
gpa_df = pd.read_csv(csv_path, encoding = "ISO-8859-1")
gpa_df.head(10)



#load the data
#data = pd.read_csv("../olympicsall.csv", encoding = "ISO-8859-1")
#data.head()

,Year,Season,City,Sport,Discipline,Athlete,Country,Population,GDP per Capita,Gender,Event,Medal
0,1896,Summer,Athens,Aquatics,Swimming,"HAJOS, Alfred",Hungary,9844686.0,12363.54,Men,100M Freestyle,Gold
1,1896,Summer,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",Austria,8611088.0,43774.99,Men,100M Freestyle,Silver
2,1896,Summer,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",Greece,10823732.0,18002.23,Men,100M Freestyle For Sailors,Bronze
3,1896,Summer,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",Greece,10823732.0,18002.23,Men,100M Freestyle For Sailors,Gold
4,1896,Summer,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",Greece,10823732.0,18002.23,Men,100M Freestyle For Sailors,Silver
5,1896,Summer,Athens,Aquatics,Swimming,"CHOROPHAS, Efstathios",Greece,10823732.0,18002.23,Men,1200M Freestyle,Bronze
6,1896,Summer,Athens,Aquatics,Swimming,"HAJOS, Alfred",Hungary,9844686.0,12363.54,Men,1200M Freestyle,Gold
7,1896,Summer,Athens,Aquatics,Swimming,"ANDREOU, Joannis",Greece,10823732.0,18002.23,Men,1200M Freestyle,Silver
8,1896,Summer,Athens,Aquatics,Swimming,"CHOROPHAS, Efstathios",Greece,10823732.0,18002.23,Men,400M Freestyle,Bronze
9,1896,Summer,Athens,Aquatics,Swimming,"NEUMANN, Paul",Austria,8611088.0,43774.99,Men,400M Freestyle,Gold

In [58]:
gpa_df.shape

(36935, 12)

In [59]:
# Calculate the number of unique country in the DataFrame
country_count = len(gpa_df["Country"].unique())

# Calculate the earliest/latest year a medal was won
earliest_year = gpa_df["Year"].min()
latest_year = gpa_df["Year"].max()

# Calculate the total medals for the entire dataset
total_medal = gpa_df["Medal"].count()

In [60]:
# Place all of the data found into a summary DataFrame
summary_table = pd.DataFrame({"Total Unique Country":country_count,
                             "Earliest Year":[earliest_year],
                             "Latest Year":[latest_year],
                             "Total Medals":[total_medal]})
summary_table

   Earliest Year  Latest Year  Total Medals  Total Unique Country
0           1896         2014         36935                   131

In [61]:
#reduced_gpa=gpa_df.drop[gpa_df.index[0,12716]]

In [62]:
#reduced the rows and starting from 1972 to adjust the GDP data is baded on current year.
reduced_df = gpa_df[gpa_df["Year"] >= 1972]
reduced_df.head(10)

,Year,Season,City,Sport,Discipline,Athlete,Country,Population,GDP per Capita,Gender,Event,Medal
12715,1972,Summer,Munich,Aquatics,Diving,"CAGNOTTO, Giorgio Franco",Italy,60802085.0,29957.80,Men,10M Platform,Bronze
12716,1972,Summer,Munich,Aquatics,Diving,"DIBIASI, Klaus",Italy,60802085.0,29957.80,Men,10M Platform,Gold
12717,1972,Summer,Munich,Aquatics,Diving,"RYDZE, Richard Anthony",United States,321418820.0,56115.72,Men,10M Platform,Silver
12718,1972,Summer,Munich,Aquatics,Diving,"JANICKE, Marina",NaN,NaN,NaN,Women,10M Platform,Bronze
12719,1972,Summer,Munich,Aquatics,Diving,"KNAPE-LINDBERGH, Ulrika",Sweden,9798871.0,50579.67,Women,10M Platform,Gold
12720,1972,Summer,Munich,Aquatics,Diving,"DUCHKOVA, Milena",NaN,NaN,NaN,Women,10M Platform,Silver
12721,1972,Summer,Munich,Aquatics,Diving,"LINCOLN, Craig Howard",United States,321418820.0,56115.72,Men,3M Springboard,Bronze
12722,1972,Summer,Munich,Aquatics,Diving,"VASIN, Vladimir",NaN,NaN,NaN,Men,3M Springboard,Gold
12723,1972,Summer,Munich,Aquatics,Diving,"CAGNOTTO, Giorgio Franco",Italy,60802085.0,29957.80,Men,3M Springboard,Silver
12724,1972,Summer,Munich,Aquatics,Diving,"JANICKE, Marina",NaN,NaN,NaN,Women,3M Springboard,Bronze

In [63]:
reduced_df.shape

(22832, 12)

In [64]:
# Group student data by school
groupedCountry_df = reduced_df.groupby(["Country"], as_index=False)
groupedCountry_df.head(5)

,Year,Season,City,Sport,Discipline,Athlete,Country,Population,GDP per Capita,Gender,Event,Medal
12715,1972,Summer,Munich,Aquatics,Diving,"CAGNOTTO, Giorgio Franco",Italy,60802085.0,29957.80,Men,10M Platform,Bronze
12716,1972,Summer,Munich,Aquatics,Diving,"DIBIASI, Klaus",Italy,60802085.0,29957.80,Men,10M Platform,Gold
12717,1972,Summer,Munich,Aquatics,Diving,"RYDZE, Richard Anthony",United States,321418820.0,56115.72,Men,10M Platform,Silver
12718,1972,Summer,Munich,Aquatics,Diving,"JANICKE, Marina",NaN,NaN,NaN,Women,10M Platform,Bronze
12719,1972,Summer,Munich,Aquatics,Diving,"KNAPE-LINDBERGH, Ulrika",Sweden,9798871.0,50579.67,Women,10M Platform,Gold
12720,1972,Summer,Munich,Aquatics,Diving,"DUCHKOVA, Milena",NaN,NaN,NaN,Women,10M Platform,Silver
12721,1972,Summer,Munich,Aquatics,Diving,"LINCOLN, Craig Howard",United States,321418820.0,56115.72,Men,3M Springboard,Bronze
12722,1972,Summer,Munich,Aquatics,Diving,"VASIN, Vladimir",NaN,NaN,NaN,Men,3M Springboard,Gold
12723,1972,Summer,Munich,Aquatics,Diving,"CAGNOTTO, Giorgio Franco",Italy,60802085.0,29957.80,Men,3M Springboard,Silver
12724,1972,Summer,Munich,Aquatics,Diving,"JANICKE, Marina",NaN,NaN,NaN,Women,3M Springboard,Bronze
12725,1972,Summer,Munich,Aquatics,Diving,"KING, Maxine Joyce",United States,321418820.0,56115.72,Women,3M Springboard,Gold
12726,1972,Summer,Munich,Aquatics,Diving,"KNAPE-LINDBERGH, Ulrika",Sweden,9798871.0,50579.67,Women,3M Springboard,Silver
12727,1972,Summer,Munich,Aquatics,Swimming,"MURPHY, John Joseph",United States,321418820.0,56115.72,Men,100M Backstroke,Bronze
12728,1972,Summer,Munich,Aquatics,Swimming,"MATTHES, Roland",NaN,NaN,NaN,Men,100M Backstroke,Gold
12729,1972,Summer,Munich,Aquatics,Swimming,"STAMM, Michael Eugene",United States,321418820.0,56115.72,Men,100M Backstroke,Silver
12732,1972,Summer,Munich,Aquatics,Swimming,"GYARMATI, Andrea",Hungary,9844686.0,12363.54,Women,100M Backstroke,Silver
12734,1972,Summer,Munich,Aquatics,Swimming,"TAGUCHI, Nobutaka",Japan,126958472.0,32477.22,Men,100M Breaststroke,Gold
12736,1972,Summer,Munich,Aquatics,Swimming,"WHITFIELD, Beverley Joy",Australia,23781169.0,56310.96,Women,100M Breaststroke,Bronze
12741,1972,Summer,Munich,Aquatics,Swimming,"ROBERTSON, Bruce Richard",Canada,35851774.0,43248.53,Men,100M Butterfly,Silver
12742,1972,Summer,Munich,Aquatics,Swimming,"GYARMATI, Andrea",Hungary,9844686.0,12363.54,Women,100M Butterfly,Bronze
12743,1972,Summer,Munich,Aquatics,Swimming,"AOKI, Mayumi",Japan,126958472.0,32477.22,Women,100M Butterfly,Gold
12748,1972,Summer,Munich,Aquatics,Swimming,"GOULD, Shane",Australia,23781169.0,56310.96,Women,100M Freestyle,Bronze
12753,1972,Summer,Munich,Aquatics,Swimming,"WINDEATT, Graham Claud",Australia,23781169.0,56310.96,Men,1500M Freestyle,Silver
12757,1972,Summer,Munich,Aquatics,Swimming,"GURR, Donna Marie",Canada,35851774.0,43248.53,Women,200M Backstroke,Bronze
12760,1972,Summer,Munich,Aquatics,Swimming,"TAGUCHI, Nobutaka",Japan,126958472.0,32477.22,Men,200M Breaststroke,Bronze
12762,1972,Summer,Munich,Aquatics,Swimming,"WILKIE, David Andrew",United Kingdom,65138232.0,43875.97,Men,200M Breaststroke,Silver
12764,1972,Summer,Munich,Aquatics,Swimming,"WHITFIELD, Beverley Joy",Australia,23781169.0,56310.96,Women,200M Breaststroke,Gold
12776,1972,Summer,Munich,Aquatics,Swimming,"GOULD, Shane",Australia,23781169.0,56310.96,Women,200M Freestyle,Gold
12779,1972,Summer,Munich,Aquatics,Swimming,"LARSSON, Gunnar",Sweden,9798871.0,50579.67,Men,200M Individual Medley,Gold
12789,1972,Summer,Munich,Aquatics,Swimming,"CALLIGARIS, Novella",Italy,60802085.0,29957.80,Women,400M Freestyle,Silver
...,...,...,...,...,...,...,...,...,...,...,...,...
29127,2008,Summer,Beijing,Weightlifting,Weightlifting,"MARTIROSYAN, Tigran Gevorg",Armenia,3017712.0,3489.13,Men,69KG,Bronze
29180,2008,Summer,Beijing,Wrestling,Wrestling Free.,"ABDUSALOMOV, Yusup",Tajikistan,8481855.0,925.91,Men,74 - 84KG,Silver
29194,2008,Summer,Beijing,Wrestling,Wrestling Gre-R,"TIUMENBAEV, Ruslan",Kyrgyzstan,5957000.0,1103.22,Men,55 - 60KG,Bronze
29200,2008,Summer,Beijing,Wrestling,Wrestling Gre-R,"BEGALIEV, Kanatbek",Kyrgyzstan,5957000.0,1103.22,Men,60 - 66KG,Silver
29252,2012,Summer,London,Aquatics,Marathon swimming,"MELLOULI, Oussama",Tunisia,11107800.0,3872.51,Men,10KM,Gold
29284,2012,Summer,London,Aquatics,Swimming,"MELLOULI, Oussama",Tunisia,11107800.0,3872.51,Men,1500M Freestyle,Bronze
29605,2012,Summer,London,Athletics,Athletics,"JAMAL, Maryam Yusuf",Bahrain,1377237.0,22600.21,Women,1500M,Bronze
29616,2012,Summer,London,Athletics,Athletics,"BARRONDO, Erick",Guatemala,16342897.0,3903.48,Men,20KM Walk,Silver
29624,2012,Summer,London,Athletics,Athletics,"JAMES, Kirani",Grenada,106825.0,9212.02,Men,400M,Gold
29625,2012,Summer,London,Athletics,Athletics,"SANTOS, Luguelin",Dominican Republic,10528391.0,6468.47,Men,400M,Silver
29705,2012,Summer,London,Athletics,Athletics,"AMOS, Nijel",Botswana,2262485.0,6360.14,Men,800M,Silver
29730,2012,Summer,London,Athletics,Athletics,"BARSHIM, Mutaz Essa",Qatar,2235355.0,73653.39,Men,High Jump,Bronze
29748,2012,Summer,London,Athletics,Athletics,"KIPROTICH, Stephen",Uganda,39032383.0,705.29,Men,Marathon,Gold
29899,2012,Summer,London,Boxing,Boxing,"CHORIEVA, Mavzuna",Tajikistan,8481855.0,925.91,Women,60 KG,Bronze
30025,2012,Summer,London,Cycling,Cycling Track,"LEE, Wai Sze",Hong Kong*,7305700.0,42327.84,Women,Keirin,Bronze
30122,2012,Summer,London,Equestrian,Jumping,"AL DUHAMI, Ramzy",Saudi Arabia,31540372.0,20481.75,Men,Team,Bronze
30123,2012,Summer,London,Equestrian,Jumping,"AL SAUD, HRH Prince Abdullah",Saudi Arabia,31540372.0,20481.75,Men,Team,Bronze
30124,2012,Summer,London,Equestrian,Jumping,"BAHAMDAN, Kamal",Saudi Arabia,31540372.0,20481.75,Men,Team,Bronze
30816,2012,Summer,London,Sailing,Sailing,"KONTIDES, Pavlos",Cyprus,1165300.0,23242.84,Men,Laser,Silver
30868,2012,Summer,London,Shooting,Shooting,"AL-ATTIYAH, Nasser",Qatar,2235355.0,73653.39,Men,Skeet,Bronze
30874,2012,Summer,London,Shooting,Shooting,"ALDEEHANI, Fehaid",Kuwait,3892115.0,29300.58,Men,Trap,Bronze
30915,2012,Summer,London,Taekwondo,Taekwondo,"OBAME, Anthony",Gabon,1725292.0,8266.45,Men,+ 80 KG,Silver
30929,2012,Summer,London,Taekwondo,Taekwondo,"NIKPAI, Rohullah",Afghanistan,32526562.0,594.32,Men,58 - 68 KG,Bronze
32909,1976,Winter,Innsbruck,Skiing,Alpine Skiing,"FROMMELT, Willy",Liechtenstein,37531.0,0.00,Men,Slalom,Bronze
32912,1976,Winter,Innsbruck,Skiing,Alpine Skiing,"WENZEL, Hanni",Liechtenstein,37531.0,0.00,Women,Slalom,Bronze
33120,1980,Winter,Lake Placid,Skiing,Alpine Skiing,"WENZEL, Hanni",Liechtenstein,37531.0,0.00,Women,Downhill,Silver
33123,1980,Winter,Lake Placid,Skiing,Alpine Skiing,"WENZEL, Andreas",Liechtenstein,37531.0,0.00,Men,Giant Slalom,Silver
33125,1980,Winter,Lake Placid,Skiing,Alpine Skiing,"WENZEL, Hanni",Liechtenstein,37531.0,0.00,Women,Giant Slalom,Gold
33892,1992,Winter,Albertville,Skiing,Alpine Skiing,"GIRARDELLI, Marc",Luxembourg,569676.0,101449.97,Men,Giant Slalom,Silver
33904,1992,Winter,Albertville,Skiing,Alpine Skiing,"GIRARDELLI, Marc",Luxembourg,569676.0,101449.97,Men,Super-G,Silver

In [65]:
groupedCountry_df.tail(5)

,Year,Season,City,Sport,Discipline,Athlete,Country,Population,GDP per Capita,Gender,Event,Medal
12938,1972,Summer,Munich,Athletics,Athletics,"AKII-BUA, John",Uganda,39032383.0,705.29,Men,400M Hurdles,Gold
13095,1972,Summer,Munich,Boxing,Boxing,"RWABDOGO, Leo",Uganda,39032383.0,705.29,Men,48 - 51KG (Flyweight),Silver
13108,1972,Summer,Munich,Boxing,Boxing,"DABORG, Issaka",Niger,19899120.0,358.96,Men,60 - 63.5KG (Light-Welterweight),Bronze
13830,1972,Summer,Munich,Weightlifting,Weightlifting,"TARABULSI, Kheir Mohamed",Lebanon,5850743.0,8047.65,Men,"67.5 - 75KG, Total (Middleweight)",Silver
14288,1976,Summer,Montreal,Boxing,Boxing,"HILL, Clarence",Bermuda*,65235.0,0.00,Men,+ 81KG (Heavyweight),Bronze
15402,1980,Summer,Moscow,Athletics,Athletics,"BAYI, Filbert",Tanzania,53470420.0,878.98,Men,3000M Steeplechase,Silver
15462,1980,Summer,Moscow,Athletics,Athletics,"NYAMBUI, Suleiman",Tanzania,53470420.0,878.98,Men,5000M,Silver
15604,1980,Summer,Moscow,Boxing,Boxing,"ANTHONY, Michael",Guyana,767085.0,4127.35,Men,51 - 54KG (Bantamweight),Bronze
15623,1980,Summer,Moscow,Boxing,Boxing,"MUGABI, John",Uganda,39032383.0,705.29,Men,63.5 - 67KG (Welterweight),Silver
16565,1980,Summer,Moscow,Wrestling,Wrestling Gre-R,"BCHARA, Hassan",Lebanon,5850743.0,8047.65,Men,+ 100KG (Super Heavyweight),Bronze
16829,1984,Summer,Los Angeles,Athletics,Athletics,"TIACOH, Gabriel",Cote d'Ivoire,22701556.0,1398.99,Men,400M,Silver
17024,1984,Summer,Los Angeles,Boxing,Boxing,"MWILA, Keith",Zambia,16211767.0,1304.88,Men,- 48KG (Light-Flyweight),Bronze
17040,1984,Summer,Los Angeles,Boxing,Boxing,"CATARI PERAZA, Omar",Venezuela,31108083.0,0.00,Men,54 - 57KG (Featherweight),Bronze
17059,1984,Summer,Los Angeles,Boxing,Boxing,"GONZALEZ, Aristides",Puerto Rico*,3474182.0,0.00,Men,71-75KG,Bronze
18020,1984,Summer,Los Angeles,Wrestling,Wrestling Free.,"ATIYEH, Josep",Syria,18502413.0,0.00,Men,90 - 100KG (Heavyweight),Silver
18076,1988,Summer,Seoul,Aquatics,Swimming,"NESTY, Anthony Conrad",Suriname,542975.0,9485.32,Men,100M Butterfly,Gold
18113,1988,Summer,Seoul,Aquatics,Swimming,"POLL AHRENS, Silvia",Costa Rica,4807850.0,11260.09,Women,200M Freestyle,Silver
18324,1988,Summer,Seoul,Athletics,Athletics,"DIA BA, El Hadji Amadou",Senegal,15129273.0,899.58,Men,400M Hurdles,Silver
18422,1988,Summer,Seoul,Athletics,Athletics,"AHMED SALAH, Hussein",Djibouti,887861.0,1945.12,Men,Marathon,Bronze
18513,1988,Summer,Seoul,Boxing,Boxing,"SERANTES, Leopoldo",Philippines,100699395.0,2904.20,Men,- 48KG (Light-Flyweight),Bronze
19323,1988,Summer,Seoul,Sailing,Sailing,"BOERSMA, Jan D.",Netherlands Antilles*,0.0,0.00,Men,Board (Division Ii),Silver
19341,1988,Summer,Seoul,Sailing,Sailing,"HOLMBERG, Peter",Virgin Islands*,103574.0,0.00,Men,Single-Handed Dinghy (Finn),Silver
19503,1988,Summer,Seoul,Volleyball,Volleyball,"PEREZ DEL SOLAR, Gabriela",Peru,31376670.0,6027.13,Women,Volleyball,Silver
19504,1988,Summer,Seoul,Volleyball,Volleyball,"TAIT, Cecilia",Peru,31376670.0,6027.13,Women,Volleyball,Silver
19505,1988,Summer,Seoul,Volleyball,Volleyball,"TORREALVA, Gina",Peru,31376670.0,6027.13,Women,Volleyball,Silver
19506,1988,Summer,Seoul,Volleyball,Volleyball,"URIBE, Cenaida",Peru,31376670.0,6027.13,Women,Volleyball,Silver
19621,1992,Summer,Barcelona,Aquatics,Swimming,"NESTY, Anthony Conrad",Suriname,542975.0,9485.32,Men,100M Butterfly,Bronze
19860,1992,Summer,Barcelona,Athletics,Athletics,"FREDERICKS, Frank",Namibia,2458830.0,4673.57,Men,100M,Silver
19870,1992,Summer,Barcelona,Athletics,Athletics,"SULAIMAN, Mohamed Ahmed",Qatar,2235355.0,73653.39,Men,1500M,Bronze
19878,1992,Summer,Barcelona,Athletics,Athletics,"FREDERICKS, Frank",Namibia,2458830.0,4673.57,Men,200M,Silver
...,...,...,...,...,...,...,...,...,...,...,...,...
36905,2014,Winter,Sochi,Skiing,Snowboard,"WILD, Vic",Russia,144096812.0,9092.58,Men,Giant Parall.S.,Gold
36906,2014,Winter,Sochi,Skiing,Snowboard,"KOSIR, Zan",Slovenia,2063768.0,20726.54,Men,Giant Parall.S.,Bronze
36907,2014,Winter,Sochi,Skiing,Snowboard,"GALMARINI, Nevin",Switzerland,8286976.0,80945.08,Men,Giant Parall.S.,Silver
36908,2014,Winter,Sochi,Skiing,Snowboard,"HIRANO, Ayumu",Japan,126958472.0,32477.22,Men,Half-Pipe,Silver
36909,2014,Winter,Sochi,Skiing,Snowboard,"HIRAOKA, Taku",Japan,126958472.0,32477.22,Men,Half-Pipe,Bronze
36910,2014,Winter,Sochi,Skiing,Snowboard,"PODLADTCHIKOV, Iouri",Switzerland,8286976.0,80945.08,Men,Half-Pipe,Gold
36911,2014,Winter,Sochi,Skiing,Snowboard,"KARL, Benjamin",Austria,8611088.0,43774.99,Men,Parallel Slalom,Bronze
36912,2014,Winter,Sochi,Skiing,Snowboard,"WILD, Vic",Russia,144096812.0,9092.58,Men,Parallel Slalom,Gold
36913,2014,Winter,Sochi,Skiing,Snowboard,"KOSIR, Zan",Slovenia,2063768.0,20726.54,Men,Parallel Slalom,Silver
36914,2014,Winter,Sochi,Skiing,Snowboard,"MCMORRIS, Mark",Canada,35851774.0,43248.53,Men,Slopestyle,Bronze
36915,2014,Winter,Sochi,Skiing,Snowboard,"SANDBECH, Staale",Norway,5195921.0,74400.37,Men,Slopestyle,Silver
36916,2014,Winter,Sochi,Skiing,Snowboard,"KOTSENBURG, Sage",United States,321418820.0,56115.72,Men,Slopestyle,Gold
36917,2014,Winter,Sochi,Skiing,Snowboard,"VAULTIER, Pierre",France,66808385.0,36205.57,Men,Snowboard Cross,Gold
36918,2014,Winter,Sochi,Skiing,Snowboard,"OLYUNIN, Nikolay",Russia,144096812.0,9092.58,Men,Snowboard Cross,Silver
36919,2014,Winter,Sochi,Skiing,Snowboard,"DEIBOLD, Alex",United States,321418820.0,56115.72,Men,Snowboard Cross,Bronze
36920,2014,Winter,Sochi,Skiing,Snowboard,"TAKEUCHI, Tomoka",Japan,126958472.0,32477.22,Women,Giant Parall.S.,Silver
36921,2014,Winter,Sochi,Skiing,Snowboard,"ZAVARZINA, Alena",Russia,144096812.0,9092.58,Women,Giant Parall.S.,Bronze
36922,2014,Winter,Sochi,Skiing,Snowboard,"KUMMER, Patrizia",Switzerland,8286976.0,80945.08,Women,Giant Parall.S.,Gold
36923,2014,Winter,Sochi,Skiing,Snowboard,"BRIGHT, Torah",Australia,23781169.0,56310.96,Women,Half-Pipe,Silver
36924,2014,Winter,Sochi,Skiing,Snowboard,"CLARK, Kelly",United States,321418820.0,56115.72,Women,Half-Pipe,Bronze
36925,2014,Winter,Sochi,Skiing,Snowboard,"FARRINGTON, Kaitlyn",United States,321418820.0,56115.72,Women,Half-Pipe,Gold
36926,2014,Winter,Sochi,Skiing,Snowboard,"DUJMOVITS, Julia",Austria,8611088.0,43774.99,Women,Parallel Slalom,Gold
36927,2014,Winter,Sochi,Skiing,Snowboard,"KARSTENS, Anke",Germany,81413145.0,41313.31,Women,Parallel Slalom,Silver
36928,2014,Winter,Sochi,Skiing,Snowboard,"KOBER, Amelie",Germany,81413145.0,41313.31,Women,Parallel Slalom,Bronze
36929,2014,Winter,Sochi,Skiing,Snowboard,"RUKAJARVI, Enni",Finland,5482013.0,42311.04,Women,Slopestyle,Silver
36930,2014,Winter,Sochi,Skiing,Snowboard,"JONES, Jenny",United Kingdom,65138232.0,43875.97,Women,Slopestyle,Bronze
36931,2014,Winter,Sochi,Skiing,Snowboard,"ANDERSON, Jamie",United States,321418820.0,56115.72,Women,Slopestyle,Gold
36932,2014,Winter,Sochi,Skiing,Snowboard,"MALTAIS, Dominique",Canada,35851774.0,43248.53,Women,Snowboard Cross,Silver
36933,2014,Winter,Sochi,Skiing,Snowboard,"SAMKOVA, Eva",Czech Republic,10551219.0,17548.34,Women,Snowboard Cross,Gold
36934,2014,Winter,Sochi,Skiing,Snowboard,"TRESPEUCH, Chloe",France,66808385.0,36205.57,Women,Snowboard Cross,Bronze

In [66]:
MedalCount_df = pd.DataFrame(groupedCountry_df["Medal"].count())

In [67]:
MedalCount_df.head()

       Country  Medal
0  Afghanistan      2
1      Algeria     15
2    Argentina    174
3      Armenia     11
4    Australia    947

In [68]:
#Tot_GDP= GDP per Capita * Population
#Nominal_GDP= reduced_df["GDP per Capita"].value*reduced_df["Polulation"].value

In [69]:
#reduced_df[Nominal] = reduced_df[float('Population')] * reduced_df[float('GDP per Capita')]